### PR TITLE
buy button and free trial changes

### PR DESCRIPTION
**Pull request by architkshk**
https://github.com/coding-blocks/codingblocks.online.projectx/pull/244 @witty123

### CODE REVIEW

**Comment by witty123** [comment]
@architkshk can you add screenshots for different screen widths.

**Comment by architkshk** [comment]
screenshot from 2018-08-13 16-20-52
screenshot from 2018-08-13 16-21-04
screenshot from 2018-08-13 16-21-09

**Comment by architkshk** [comment]
@witty123 
screenshot from 2018-08-13 18-11-43
screenshot from 2018-08-13 18-11-48
screenshot from 2018-08-13 18-11-56
screenshot from 2018-08-13 18-11-59

**Comment by witty123** [comment]
You'll have to left align the course progress component in case of smaller screen sizes.

**Comment by architkshk** [comment]
that would be done on https://github.com/coding-blocks/codingblocks.online.projectx/pull/244
@witty123 
screenshot from 2018-08-14 02-35-07
Does this look fine?

**Pull request merged**
