### PR TITLE
fix overflow in doubts section

### PR DESCRIPTION
**Pull request by architkshk**
in reference to https://github.com/coding-blocks/codingblocks.online.projectx/issues/109
@witty123 please check
screenshot from 2018-06-11 18-22-52

### CODE REVIEW

**Comment by witty123** [comment]
@architkshk you wont have access to html elements inside   <div class="doubt-body">
 have a look at this file https://github.com/coding-blocks/codingblocks.online.projectx/blob/master/app/pods/components/doubt-view/template.hbs

**Comment by architkshk** [comment]
@witty123 changed to nth-child on doubt-body. is that accessible?

**Comment by witty123** [comment]
by nth child you are just accessing every element. I'll tell you a better way to do it. You can create a pre-wrap class which we can use elsewhere as well wherever we are using markdown. For creating that class you can either use the trump layer or the element layer for pre tag

**Comment by architkshk** [comment]
Ok @witty123 , I can create a class to add on pre element created by markdown to HTML converter. Later hook that to markdown using showdown extension.
https://github.com/showdownjs/showdown/wiki/Add-default-classes-for-each-HTML-element

**Comment by witty123** [comment]
I guess this is fine for now. No point in generalising since we wont be using it elsewhere.

**Comment by architkshk** [comment]
@witty123 , this fixes overflow for mobile devices too.

**Comment by witty123** [comment]
Attach screenshots when done with the changes.

**Comment by witty123** [comment]
screen shot 2018-06-12 at 1 54 40 pm

**Comment by architkshk** [comment]
screenshot from 2018-06-12 14-20-49

**Pull request merged**
