### PR TITLE
Highlight current content #2

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 done, please have a look

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 updates?

**Comment by witty123** [comment]
@VibhorCodecianGupta resolve conflicts please.

**Comment by VibhorCodecianGupta** [comment]
@witty123 done

**Comment by witty123** [comment]
@VibhorCodecianGupta please make corresponding PR on online cb as well

**Comment by VibhorCodecianGupta** [comment]
working on it

**Pull request closed without merging**
