### PR TITLE
Transition page

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
@abhishek97 related to https://github.com/coding-blocks/codingblocks.online.projectx/issues/258

### CODE REVIEW

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 @witty123 any updates here? resolved conflicts

**Comment by abhishek97** [comment]
@VibhorCodecianGupta can you add screenshots, this is all i see on transition.html

screen shot 2018-08-15 at 10 36 52 pm

**Comment by VibhorCodecianGupta** [comment]
refactoring motley broke this page. Will fix and commit

**Comment by VibhorCodecianGupta** [comment]
@abhishek97 fixed the view. This was committed yesterday before BOSS ended, but due to some massive technical difficulties, I had no internet and hence i couldn't push this. For the very same reason I also couldn't claim any bounties for my PRs submitted in the last few days. In case my design gets accepted (200 bounty) and this DOM implementation gets merged (500 bounty), it'd be great if you could provide me bounty for that since I can no longer do it.

Also, can we still resolve pending issues and claim them?

screen shot 2018-08-16 at 6 01 54 pm

**Comment by witty123** [comment]
@VibhorCodecianGupta BOSS has officially ended now and you can only work on the PRs for which you've already raised claims and there's some pending work remaining on them.
Your concern is valid but it'll be very difficult for us to incorporate your request. I'll still discuss with team and see if its possible for us to distribute bounties like this.

**Comment by VibhorCodecianGupta** [comment]
@witty123 I completely understand, it is very unfortunate. Again, I'm just requesting for the PRs which were accepted with some changes (like this one, the design of this on online cb, the design of the current content active class and its implementation in motley). By all means, do what you deem appropriate. I had a similar conversation with @championswimmer here, please check comments
https://github.com/coding-blocks/oneauth/pull/349

**Comment by vdvibhu20** [comment]
@VibhorCodecianGupta This thing breaks on Mobile and Tab screens

**Comment by vdvibhu20** [comment]
@VibhorCodecianGupta Remove image from the background and add video player in place of it.
Refer to `examples/views/timeline.hbs`

**Comment by VibhorCodecianGupta** [comment]
@vdvibhu20 @witty123 done, please review

**Comment by VibhorCodecianGupta** [comment]
@vdvibhu20 @witty123

**Comment by abhishek97** [comment]
LGTM @vdvibhu20

**Pull request closed without merging**
