### PR TITLE
Added SVG icons

### PR DESCRIPTION
**Pull request by VibhorCodecianGupta**
Original issue:
https://github.com/coding-blocks/codingblocks.online.projectx/issues/90

Original PR:
https://github.com/coding-blocks/codingblocks.online.projectx/pull/98
(First PR to the issue)

For screenshots, refer 
https://github.com/coding-blocks/codingblocks.online.projectx/pull/98

### CODE REVIEW

**Comment by witty123** [comment]
Closing this in favour of #173

**Comment by VibhorCodecianGupta** [comment]
Why was this closed? No reviews/suggestions/improvements? @witty123 @abhishek97 ?

**Comment by VibhorCodecianGupta** [comment]
I thought so. @witty123 actually sir, my PR was the first on the parent issue, which is why I mentioned that here. Just that the other contributor was informed before me that the PR had to be made on motley instead of projectx. Hence my PR to motley was second to them. With all due respect, the original issue saw my PR first :)

**Comment by VibhorCodecianGupta** [comment]
@witty123 doesn't matter now, kinda had this same experience about thrice now in my previous PRs to various issues. I think I'll go ahead and withdraw from BOSS. It'd really take the competition up a notch if there'd be contribution guidelines for participants/contributors :)

**Comment by witty123** [comment]
@VibhorCodecianGupta Really sorry that you had this experience. We will work our best to improve BOSS in coming years. Contribution guidelines for participants is something we are already working on and the future PRs will be governed by that. Since this is an issue on our end, let me know if I can change your decision of withdrawing by giving you a bonus 200 BOUNTY points instead. We will take extreme caution for all the future PRs.

**Comment by VibhorCodecianGupta** [comment]
Appreciate it a lot! It's alright though, no need for the extra bounty :)
I'll contribute anyway, I love doing this :)

**Comment by VibhorCodecianGupta** [comment]
That'll be amazing if you could do that, appreciate it a lot :D
I'll continue contributing, I like doing this. Also, because this has come up now, do you guys have some basic points jotted down for the enhanced contribution guidelines (seeing that the current ones are pretty basic and just explain the workflow rather than how they will be evaluated, which is just as important I guess)? If not, this could be a valid issue and we could start working on it, there are plenty of bounty offering organizations and their guidelines could be a reference point for BOSS.
@witty123

**Comment by witty123** [comment]
http://lab.codingblocks.com/boss 
You can find the guidelines here, feel free to submit PRs for any corrections https://github.com/coding-blocks/boss

**Comment by VibhorCodecianGupta** [comment]
@witty123

**Comment by witty123** [comment]
Yes please open the issue in BOSS repo and I'll ask all mentors to help you out regarding the guidelines. Bonus bounty you can claim with this PR.

**Pull request closed without merging**
