### PR TITLE
overflow of difficulty fixed

### PR DESCRIPTION
**Pull request by harshTTH**

### CODE REVIEW

**Comment by harshTTH** [comment]
screenshot from 2018-05-31 00-37-30

**Comment by harshTTH** [comment]
its just the chrome extension doing so, will upload the original screenshot, this image is posted by mistake

**Comment by witty123** [comment]
@harshTTH  Please write all the media queries in media query sub folder.

**Comment by witty123** [comment]
Closing due to inactivity. Please reopen after done with the changes.

**Pull request closed without merging**
