### PR TITLE
added css for skeleton cards loader

### PR DESCRIPTION
**Pull request by hereisnaman**
fixes: https://github.com/coding-blocks/motley/issues/134

the required html changes are here: https://github.com/coding-blocks/codingblocks.online.projectx/pull/66

Have removed the css changes from the PR on projectX.

### CODE REVIEW

**Comment by aayusharora** [comment]
Please check my comment here  coding-blocks/codingblocks.online.projectx#66

**Comment by championswimmer** [comment]
@aayusharora @abhishek97 whats the status on this ?

**Comment by abhishek97** [comment]
@hereisnaman please add an example `.hbs` file here also, containing just this component in loading state. Also I've updated https://github.com/coding-blocks/codingblocks.online.projectx/pull/66 with a svg, which might help you in animation.

**Comment by hereisnaman** [comment]
@abhishek97 that new svg won't make any difference. need opaque bg with transparent placeholders.

**Comment by witty123** [comment]
@abhishek97 @aayusharora 
 if search box is an element according to current structure then we can keep loading card as an element as well.

**Comment by aayusharora** [comment]
This looks good to me @witty123 @championswimmer

**Comment by witty123** [comment]
@aayusharora corresponding PR on online codingblocks has been inactive since long. I'd say lets close both the PRs. Bump up the bounty points on the issue and lets see if someone can come up with a solution by either building upon the existing one or propose a new one.

**Comment by witty123** [comment]
Closed in favour of https://github.com/coding-blocks/motley/pull/233

**Pull request closed without merging**
