### PR TITLE
reply-btn-fix

### LINKED ISSUE #133: incorrect width of reply now button in ask your doubt section
<a href="https://github.com/architkshk"></img></a> **Issue by [architkshk](https://github.com/architkshk)**
_Wednesday May 16, 2018 at 15:06 GMT_
_Originally opened as https://github.com/coding-blocks/codingblocks.online.projectx/issues/60_

----

screenshot from 2018-05-16 20-30-48

### PR DESCRIPTION
**Pull request by architkshk**
#133

### CODE REVIEW

**Comment by abhishek97** [comment]
Please add screenshots

**Comment by architkshk** [comment]
screenshot from 2018-05-19 16-30-37

**Comment by abhishek97** [comment]
This doesn't look very good. Maybe we should wrap the button to the next line.

Something like this maybe?
screen shot 2018-05-19 at 4 42 40 pm

**Comment by architkshk** [comment]
Ok
I'll work on it.

**Comment by architkshk** [comment]
@abhishek97 Please assign a bounty to the corresponding issue.

**Comment by abhishek97** [comment]
I don't think we need to change DOM markup in this case. All the three items Author Name, No of replies and Button should be siblings. This will allow us to wrap content according to whatever order we feel like in future. The fewer changes you make the better.

**Comment by witty123** [comment]
@architkshk 
@abhishek97 will be working on the issue. Thanks for trying.

**Pull request closed without merging**
